178 Export
adam-rms/adam-rms pull request #353
Opened 2022-05-11 22:04 UTC by cherry-john

By submitting a PR for this repository you accept the contributor license agreement. 

### Description

Adds customisable export functionality for a selection of tables. More info to follow

### References
Closes #178 

### ToDo

- [ ] Add actual export endpoint
- [ ] Check data validation
- [ ] Add documentation

### Checklist

- [ ] I have added documentation for new/changed functionality in this PR or in the documentation repo
- [ ] All active GitHub checks for tests, formatting, and security are passing
- [ ] The correct base branch is being used, if not `main`

2022-05-12 05:24 UTC, Jbithell commented
I don't think we need to worry about permissions of each table tbh. If they have permission to export then we keep it simple and let them export everything

2022-05-12 06:21 UTC, cherry-john commented
> I don't think we need to worry about permissions of each table tbh. If they have permission to export then we keep it simple and let them export everything

Happy with that, makes it a lot easier. 
Thinking about it, for the rms to work well, you have to at least be able to view pretty much everything so it doesn't make a lot of sense to check!

2022-05-13 18:37 UTC, Robert-Watts commented on db/migrations/20220511160027_export_permission.php
> +            'instanceActions_dependent' => null,
I think this should depend on 12, "Edit roles permissions [SUPER ADMIN]", otherwise its v easy to tick and let someone random grab data.

2022-12-17 16:23 UTC, Jbithell requested changes
Could we remove current asset export functionality and move it into here? (and then link to this from the same places).

2022-12-17 18:42 UTC, cherry-john commented
> Could we remove current asset export functionality and move it into here? (and then link to this from the same places).

As in keep these changes for exporting or replace this with the current export method?

2022-12-17 18:49 UTC, Jbithell commented
> > Could we remove current asset export functionality and move it into here? (and then link to this from the same places).
> 
> As in keep these changes for exporting or replace this with the current export method?

As in remove what is in main for exporting to replace it with this

2023-05-11 18:11 UTC, closed without merging